language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install guessit selenium requests lxml pysynthetic"
# command to run tests
script: python3 -m unittest discover -p '*test.py'
